server:
  port: 8001
mybatis:
  type-aliases-package: com.tu.pojo
  mapper-locations: classpath:mappers/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test03?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 970524


#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


#info
info:
  app.name: tu.springcloud
  company.name: com.tu